### PR TITLE
DCT tools update

### PR DESCRIPTION
**Pull request by yfukai**
Fix deprecated logic for DCT tools. should be merged later than #95 and #96.

### CODE REVIEW

**Review by Nicholas-Schaub — DISMISSED** [review]

**Comment by yfukai** [comment]
some test are failing...

**Comment by yfukai** [comment]
```
___________________________ test_inverse_interleave ____________________________

    def test_inverse_interleave():
        x = jnp.arange(24).reshape(4, 3, 2)
    
        for axis in range(x.ndim):
>           y = jax._src.scipy.fft._dct_interleave(x, axis=axis)
E           AttributeError: module 'jax' has no attribute '_src'
```
maybe because of JAX update?

**Comment by yfukai** [comment]
even the dev test are failing after update...

**Comment by yfukai** [comment]
I fixed the test problems (by changing the way of importing `jax` hidden functions and loosening `np.isclose` a bit). Can you check this again? @Nicholas-Schaub

**Comment by yfukai** [comment]
Maybe we should consider merging `jax` things in the original repo so that it can follow the changing APIs. At this moment I just fixed the dependency version.

**Comment by yfukai** [comment]
@Nicholas-Schaub

**Review by Nicholas-Schaub — APPROVED** [review]

**Pull request merged**
