### PR TITLE
Data in package

### PR DESCRIPTION
**Pull request by yfukai**
Attempt to add getting-sample-data function to the package, following `scikit-image` etc.

### CODE REVIEW

**Comment by yfukai** [comment]
Now the test is quite slow (bounded by download?)

**Comment by yfukai** [comment]
I think I should consider compressing the data and making test data with the new implementation first and then come back to this pull request.

**Comment by Nicholas-Schaub** [comment]
Is this still WIP?

**Comment by yfukai** [comment]
A problem is that it's still slow to download the data. I I'll first reorganize the data (in image size and bit depth), make an associated test data and then open this pull request.

**Comment by Nicholas-Schaub** [comment]
@yfukai is there an ETA for this? I could assist if needed.

**Comment by yfukai** [comment]
Thanks, I'm waiting for myself to finish the implementation of the main routine #58 to generate test data, and hopefully, I'll be able to finish it by next week! If it seems to be taking more time, I'll think about an alternative way.

**Comment by yfukai** [comment]
Now it's open. The test is failing for now, but I think it works once the data added to the repo. (At least it's working if I changed the URL to https://github.com/yfukai/BaSiCpy/raw/data_in_package/data . Please let me know if it's better to separate the tests into another one.

**Comment by yfukai** [comment]
This is the test result with the URL https://github.com/yfukai/BaSiCpy/raw/data_in_package/data 
https://github.com/peng-lab/BaSiCPy/pull/57/checks?check_run_id=6551997384
@Nicholas-Schaub @tdmorello

**Comment by yfukai** [comment]
This will close #8.

**Review by Nicholas-Schaub — APPROVED** [review]

**Pull request merged**
