### PR TITLE
Adding autotune

### PR DESCRIPTION
**Pull request by yfukai**
Attempt to add autotune function to BaSiC.

### CODE REVIEW

**Comment by yfukai** [comment]
I also fixed this line, since the default argument contradicted that of the `fit` function.
https://github.com/peng-lab/BaSiCPy/blob/78613fb5cb57fec7752dff4ca9da374e6d4f726c/src/basicpy/basicpy.py#L589

**Comment by yfukai** [comment]
It seems the `hyperactive` result is not reproducible even with fixed random seeds. How would you guess the cause? @Nicholas-Schaub

**Comment by yfukai** [comment]
The result is consistent in the same architecture, maybe this is caused by the difference in JAX-compiled code...

**Comment by yfukai** [comment]
Loosened the test for now.

**Comment by yfukai** [comment]
Test is a bit more strict now, ready for review @Nicholas-Schaub .

**Comment by yfukai** [comment]
ready for review! @Nicholas-Schaub

**Review by Nicholas-Schaub — APPROVED** [review]

**Pull request merged**
