### PR TITLE
Feat/jax dct

### LINKED ISSUE #17: Implement DCT form Jax
Jax is a numerical acceleration library that should allow easy switching of computation from CPU to GPU. This is a step toward adding complete Jax support as requested in #4 

This is blocked by #15 

https://github.com/google/jax

- [ ] Add GPU settings to the DCT base class, including whether the class supports GPU as a class property and a `device` parameter to the `dct` and `idct` methods
- [x] Implement a Jax DCT class

### PR DESCRIPTION
**Pull request by tdmorello**
This pull request adds a custom implementation of the inverse discrete cosine transform (a.k.a. dct type 3).

- The function (`.tools._jax_idct.idct`) was verified against `scipy.fft.idct`, is n-dimensional, and contains an `ortho=norm` option for scaling
- `tools.dct2d_tools` was updated to include this custom function
- Tests are included

This function should eventually be replaced by `jax.scipy.idct` whenever that becomes available.

Closes #17

### CODE REVIEW

**Comment by tdmorello** [comment]
Whoops, I see that adding gpu support is a part of #17 . I will add that.

**Comment by tdmorello** [comment]
Note that the JAX `dct` and `idct` need to be somewhere inside a `@jax.jit` decoration to be fast.

**Review by yfukai — DISMISSED** [review]
I still couldn't follow the algorithm itself, but it looks good to go, given it has been tested!

**Review by Nicholas-Schaub — DISMISSED** [review]

**Comment by Nicholas-Schaub** [comment]
Just need to fix merge conflicts and it's good to go

**Review by Nicholas-Schaub — APPROVED** [review]

**Pull request merged**
