### PR TITLE
Testing fit method with synthetic data

### PR DESCRIPTION
**Pull request by yfukai**
Testing `fit` and `transform` function (#52). Assumes #51, #44 and #42 be approved and try to follow those branches.

### CODE REVIEW

**Comment by yfukai** [comment]
Reverted Zenodo dataset things for another PR.

**Comment by Nicholas-Schaub** [comment]
Is this still WIP?

**Comment by yfukai** [comment]
I wrote this code on #44 branch and would like to wait until it merged to get a clearer diff for review.

**Comment by Nicholas-Schaub** [comment]
@yfukai , it shouldn't make a difference, but #44 is now merged.

**Comment by yfukai** [comment]
Oh, maybe I misunderstood something then. Thanks anyway!

**Comment by yfukai** [comment]
Hi @Nicholas-Schaub, I remembered why I changed the input test data. The original data was not smooth enough for the BaSiC fitting (at that point, at least). I'm not sure if it makes sense to adjust the data to the algorithm, but I just switched it to a smoother function as a test.

image
image

**Review by Nicholas-Schaub — APPROVED** [review]

**Pull request merged**
