### PR TITLE
ignored pyenv `.python-version`

### PR DESCRIPTION
**Pull request by yfukai**
Tried to ignore `.python-version` for pyenvs. Is it fine to write it to repo .gitignore? Opinions are welcome!

### CODE REVIEW

**Comment by tdmorello** [comment]
Hey @yfukai , you could uncomment [this line](https://github.com/yfukai/BaSiCpy/blob/45808096042928720e347fdcb9a774d74bde9e25/.gitignore#L88) instead of adding a new line at the bottom.

**Comment by yfukai** [comment]
Didn't notice, thanks!

**Comment by yfukai** [comment]
done!

**Comment by yfukai** [comment]
Oh sorry I just noticed Tim actually made that change in 1854fbc. Anyway diff looks OK for now.

**Review by tdmorello — APPROVED** [review]

**Pull request merged**
