### PR TITLE
Add output of corrected images to example notebooks

### PR DESCRIPTION
**Pull request by jenna-tomkinson**
Hello!

In this PR, I included the following changes:

1. Rerun the [example notebooks](https://github.com/peng-lab/BaSiCPy/tree/main/docs/notebooks) so that the outputs are included in order.
2. Added comments into the notebooks for more interpretability
3. Including a last code cell in all notebooks to output the corrected images in the most optimal method (e.g., `skimage.io.imsave` from issue #91)
4. Editing paths in the main README to these updated notebooks

### CODE REVIEW

**Comment by jenna-tomkinson** [comment]
Hi @yfukai, @tying84, and @Nicholas-Schaub,

I know you all are probably super busy but wanted to give a small poke about this PR.

I am really excited to see what comments you all have 😄.

Thank you in advance!

**Comment by yfukai** [comment]
Hi @jenna-tomkinson, thank you for this pull request and I'm sorry for the late reply, I myself have been completely involved with the benchmarking for the publication (and also other projects). Right, as you point out, it is more useful if the link is directed to the notebook including the results.

Actually those notebooks are automatically executed when building the document ( https://basicpy.readthedocs.io/ ), and I believe that may better than including the executed results since
- the notebook results are automatically updated to the latest version whenever we build the document, and we can keep the notebook consistent with what the latest package does
- we can keep the repository (slightly) lighter.

About the image saving, we actually don't recommended 
- converting the images back to uint8 or uint16
- rescaling the images by min and max

since it can lead to information loss (by discretization) or new artifacts. The images can be saved as `npy` file or `tiff` images, but in a *float* format. 

With this, I was wondering how you think about 
- Changing the links to the notebook to readthedocs executed versions: (for example, https://basicpy.readthedocs.io/en/latest/notebooks/WSI_brain.html etc.)
- Keeping the notebook non-executed, but adding a cell for saving images as float `npy` file or `tiff` images.

Thanks!

**Review by yfukai — CHANGES_REQUESTED** [review]
- Changing the links to the notebooks to readthedocs executed versions: (for example, https://basicpy.readthedocs.io/en/latest/notebooks/WSI_brain.html etc.)

- Keeping the notebook non-executed, but adding a cell for saving images as float any file or tiff images.

May be a better option, thanks!

**Comment by jenna-tomkinson** [comment]
@yfukai 

Thank you for the review! I did not realize that is why the notebooks were not run, so I am glad to learn something new!

I agree with all of the comments and I can easily implement this! 

I will note, I do have competing priorities that I will be directing my attention to, so I hope to get to finishing this PR in the near future. I will be keeping this on my list of to-dos, but I probably won't get back to this for a few weeks. If it seems like it has been a very long time, please feel free to poke me.

Thank you again!

**Comment by Nicholas-Schaub** [comment]
@jenna-tomkinson I also apologize for being slow to respond. Do you still intend on completing this?

**Comment by jenna-tomkinson** [comment]
Hello @Nicholas-Schaub!

I am still interested in completing this PR, but my bandwidth this month is stretched thin with other priorities.

I will likely come back to finish this up in November.

**Comment by jenna-tomkinson** [comment]
Hello all, 

My apologies for not getting back to this PR sooner. After considerable thought, I have decided to close this PR until further notice due to other competing priorities. 

Thank you for the opportunity, and I wish you all the best of luck with this great tool!

**Pull request closed without merging**
